name: Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_DEST: ${{ secrets.SERVER_DEST }}

    steps:
      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          echo "$SSH_PUBLIC_KEY" > ~/.ssh/id_ed25519.pub
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts

      - name: Update repository
        run: ssh $SERVER_USER@$SERVER_HOST "cd $SERVER_DEST && git fetch && git reset --hard origin/main"

      - name: Install dependencies
        run: ssh $SERVER_USER@$SERVER_HOST "cd $SERVER_DEST && npm ci"

      - name: Build application
        run: ssh $SERVER_USER@$SERVER_HOST "cd $SERVER_DEST && npm run build"

      - name: Restart server
        run: ssh $SERVER_USER@$SERVER_HOST "devil www restart $SERVER_HOST"
